In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [42]:
df=pd.read_csv("heights.csv")

In [43]:
df

       name  height
0     mohan     1.2
1     maria     2.3
2     sakib     4.9
3       tao     5.1
4     virat     5.2
5    khusbu     5.4
6    dmitry     5.5
7    selena     5.5
8      john     5.6
9     imran     5.6
10     jose     5.8
11  deepika     5.9
12   yoseph     6.0
13    binod     6.1
14  gulshan     6.2
15  johnson     6.5
16   donald     7.1
17    aamir    14.5
18      ken    23.2
19      Liu    40.2

In [18]:
df.describe()

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,15.928333,4.536667,6.449417,1.740333,2.990383,1.014500,5.445833,5.636667,5.565000,0.025833
std,2.021947,2.029599,1.442677,0.716660,0.576758,0.582185,2.903290,2.859453,2.830627,0.158704
min,13.000000,1.000000,4.000000,0.500000,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,14.000000,2.800000,5.200000,1.100000,2.500000,0.500000,3.000000,3.000000,3.000000,0.000000
50%,16.000000,4.500000,6.500000,1.800000,2.990000,1.000000,5.000000,6.000000,6.000000,0.000000
75%,18.000000,6.300000,7.600000,2.400000,3.480000,1.500000,8.000000,8.000000,8.000000,0.000000
max,19.000000,8.000000,9.000000,3.000000,4.000000,2.000000,10.000000,10.000000,10.000000,1.000000

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    20 non-null     object
 1   height  20 non-null     float64
dtypes: float64(1), object(1)
memory usage: 448.0+ bytes

Outlier using IQR method

In [20]:
df.columns

Index(['age', 'gender', 'daily_social_media_hours', 'platform_usage',
       'sleep_hours', 'screen_time_before_sleep', 'academic_performance',
       'physical_activity', 'social_interaction_level', 'stress_level',
       'anxiety_level', 'addiction_level', 'depression_label'],
      dtype='object')

In [46]:
Q1=df.height.quantile(0.25)
Q3=df.height.quantile(0.75)
print(Q1)
print(Q3)

5.3500000000000005
6.275

In [47]:
IQR=Q3-Q1
IQR

np.float64(0.9249999999999998)

In [48]:
lower_limit=Q1-1.5*IQR
Upper_limit=Q3+1.5*IQR
print(lower_limit)
print(Upper_limit)

3.962500000000001
7.6625

In [52]:
Out=df[(df.height<lower_limit)| (df.height>Upper_limit)]
Out

     name  height
0   mohan     1.2
1   maria     2.3
17  aamir    14.5
18    ken    23.2
19    Liu    40.2

In [53]:
Out.size

10

In [55]:
no_out=df[(df.height>lower_limit)& (df.height<Upper_limit)]
no_out

       name  height
2     sakib     4.9
3       tao     5.1
4     virat     5.2
5    khusbu     5.4
6    dmitry     5.5
7    selena     5.5
8      john     5.6
9     imran     5.6
10     jose     5.8
11  deepika     5.9
12   yoseph     6.0
13    binod     6.1
14  gulshan     6.2
15  johnson     6.5
16   donald     7.1

In [59]:
df2=pd.read_csv("heights2.csv")

In [60]:
df2.height.mean()

np.float64(66.367559754866)

In [62]:
df2.height.std()

np.float64(3.847528120795573)

In [64]:
lower_limit2=df2.height.mean()-3*df2.height.std()
lower_limit2

np.float64(54.824975392479274)

In [65]:
Upper_limit2=df2.height.mean()+3*df2.height.std()
Upper_limit2

np.float64(77.91014411725271)

In [68]:
out=df2[(df2.height<lower_limit2)|(df2.height>Upper_limit2)]
out

      gender     height
994     Male  78.095867
1317    Male  78.462053
2014    Male  78.998742
3285    Male  78.528210
3757    Male  78.621374
6624  Female  54.616858
9285  Female  54.263133

In [69]:
No_out=df2[(df2.height>=lower_limit2)& (df2.height<=Upper_limit2)]
No_out

      gender     height
0       Male  73.847017
1       Male  68.781904
2       Male  74.110105
3       Male  71.730978
4       Male  69.881796
...      ...        ...
9995  Female  66.172652
9996  Female  67.067155
9997  Female  63.867992
9998  Female  69.034243
9999  Female  61.944246

[9993 rows x 2 columns]

In [70]:
df2["zscore"]=(df2.height-df2.height.mean())/df2.height.std()
df2

      gender     height    zscore
0       Male  73.847017  1.943964
1       Male  68.781904  0.627505
2       Male  74.110105  2.012343
3       Male  71.730978  1.393991
4       Male  69.881796  0.913375
...      ...        ...       ...
9995  Female  66.172652 -0.050658
9996  Female  67.067155  0.181830
9997  Female  63.867992 -0.649655
9998  Female  69.034243  0.693090
9999  Female  61.944246 -1.149651

[10000 rows x 3 columns]

In [71]:
df2[df2["zscore"]>3]

     gender     height    zscore
994    Male  78.095867  3.048271
1317   Male  78.462053  3.143445
2014   Male  78.998742  3.282934
3285   Male  78.528210  3.160640
3757   Male  78.621374  3.184854

In [72]:
df2[df2['zscore']<-3]

      gender     height    zscore
6624  Female  54.616858 -3.054091
9285  Female  54.263133 -3.146027

In [74]:
out=df2[(df2.zscore<-3)|(df2.zscore>3)]
out

      gender     height    zscore
994     Male  78.095867  3.048271
1317    Male  78.462053  3.143445
2014    Male  78.998742  3.282934
3285    Male  78.528210  3.160640
3757    Male  78.621374  3.184854
6624  Female  54.616858 -3.054091
9285  Female  54.263133 -3.146027

In [75]:
no_outl=df2[(df2.zscore>=-3)&(df2.zscore<=3)]
no_outl

      gender     height    zscore
0       Male  73.847017  1.943964
1       Male  68.781904  0.627505
2       Male  74.110105  2.012343
3       Male  71.730978  1.393991
4       Male  69.881796  0.913375
...      ...        ...       ...
9995  Female  66.172652 -0.050658
9996  Female  67.067155  0.181830
9997  Female  63.867992 -0.649655
9998  Female  69.034243  0.693090
9999  Female  61.944246 -1.149651

[9993 rows x 3 columns]

In [76]:
q1=df2.height.quantile(0.25)
q3=df2.height.quantile(0.75)

In [77]:
iqr=q3-q1

In [78]:
iqr

np.float64(5.668641247500005)

In [80]:
lower_l=q1-1.5*iqr
uper_l=q3+1.5*iqr
lower_l,uper_l

(np.float64(55.00265860875), np.float64(77.67722359875002))

In [82]:
outl=df2[(df2.height<lower_l)|(df2.height>uper_l)]
outl

      gender     height    zscore
994     Male  78.095867  3.048271
1317    Male  78.462053  3.143445
2014    Male  78.998742  3.282934
3285    Male  78.528210  3.160640
3757    Male  78.621374  3.184854
6624  Female  54.616858 -3.054091
7294  Female  54.873728 -2.987329
9285  Female  54.263133 -3.146027

In [83]:
No_outL=df2[(df2.height>=lower_l)&(df2.height<=uper_l)]
No_outL

      gender     height    zscore
0       Male  73.847017  1.943964
1       Male  68.781904  0.627505
2       Male  74.110105  2.012343
3       Male  71.730978  1.393991
4       Male  69.881796  0.913375
...      ...        ...       ...
9995  Female  66.172652 -0.050658
9996  Female  67.067155  0.181830
9997  Female  63.867992 -0.649655
9998  Female  69.034243  0.693090
9999  Female  61.944246 -1.149651

[9992 rows x 3 columns]